### ISSUE TITLE
Is it intentional that the v1.0.0 tag is not usable in workflows?

### ISSUE THREAD

**Issue by alexrp** [xt0rted/markdownlint-problem-matcher#168]
Hi,

I was hoping to use the most specific version of the action (i.e. `v1.0.0`) in my workflow since I like to keep things as stable/non-disruptive as possible. But it seems that that tag isn't meant to be consumed in workflows as it lacks the `dist` directory.

I just wanted to check if this is intentional?

**Comment by xt0rted** [comment]
No that's not intentional. I'm not sure what happened when I did the initial release but I guess I never noticed since I was referencing `@v1` in my workflows. I just published v1.1.0 that should fix this. It's the same as v1.0.0 but contains an update to the `@actions/core` dependency.

**Comment by alexrp** [comment]
I've updated to `v1.1.0` and can confirm it works. Thank you!
