### ISSUE TITLE
Release with Node 16

### ISSUE THREAD

**Issue by kasperg** [xt0rted/markdownlint-problem-matcher#527]
[GitHub now raise warnings when using actions using Node 12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). This project was updated to use Node 16 with #373 but the latest release is from 2020 and still uses Node 12. Have you considered releasing a new version with the update?

Thanks for sharing markdownlint-problem-matcher!

**Comment by xt0rted** [comment]
I plan on releasing new versions of all my actions over the next week or two. I'll update this when it's available.

**Comment by xt0rted** [comment]
Just released [v2.0.0](https://github.com/xt0rted/markdownlint-problem-matcher/releases/tag/v2.0.0) with this update.
